[package]
name = "audio_playback"
version = "0.1.0"
edition = "2021"

[dependencies]
dora-node-api = { workspace = true }
eyre = { workspace = true }
robo_rover_lib = { path = "../../robo_rover_lib" }
tracing = { workspace = true }
cpal = "0.15"
